In [1]:
from pathlib import Path
import os

#Nachfragen wie man das elegante lösen könnte!

# Immer sicher: Projektroot anhand dieser Datei bestimmen
notebook_dir = Path(os.getcwd())

# Nur hochgehen wenn wir noch in notebooks/ sind
if notebook_dir.name == "notebooks":
    os.chdir(notebook_dir.parent)

print(os.getcwd())  # Kontrolle: muss in sds210-final-project enden

/Users/christophhueppi/Documents/Universität_Zürich/Geographie/Master/FS-26/GEO-876/sds210-final-project

In [3]:
import pandas as pd

# 1. Load
zwn_df = pd.read_csv("data/raw/stzh.zwn_meldungen_p.csv")

print("Data loaded successfully!")

# 2. Peek
display(zwn_df.head(10))
display(zwn_df.tail(10))

# 3. Shape & Columns
print(zwn_df.shape)
print(zwn_df.columns.values)
display(zwn_df.info())

Data loaded successfully!

,objectid,service_request_id,requested_datetime,agency_sent_datetime,updated_datetime,e,n,service_code,service_name,status,userid,title,detail,media_url,interface_used,service_notice,description,url,geometry
0,1,1,2013-03-14T15:16:15,2013-04-04T07:25:05,2013-04-12T07:59:30,2678968,1247548,Strasse/Trottoir/Platz,Strasse/Trottoir/Platz,fixed - council,16624,Auf dem Asp,Auf dem Asphalt des Bürgersteigs hat es eine E...,NaN,Web interface,Diese Reparatur wird von uns in den kommenden ...,Auf dem Asp: Auf dem Asphalt des Bürgersteigs ...,https://www.zueriwieneu.ch/report/1,POINT (2678968 1247548)
1,2,2,2013-03-14T15:17:57,2013-03-26T14:05:05,2013-04-12T08:00:22,2680746,1249916,Strasse/Trottoir/Platz,Strasse/Trottoir/Platz,fixed - council,16624,Vermessungs,Vermessungspunkt ist nicht mehr bündig mit dem...,NaN,Web interface,Diese Reparatur wird von uns in den kommenden ...,Vermessungs: Vermessungspunkt ist nicht mehr b...,https://www.zueriwieneu.ch/report/2,POINT (2680746 1249916)
2,3,4,2013-03-15T09:14:16,2013-03-15T09:55:05,2013-04-12T08:08:10,2684605,1251431,Strasse/Trottoir/Platz,Strasse/Trottoir/Platz,fixed - council,16624,Beim Trotto,Beim Trottoir sind einige Randsteine defekt un...,https://www.zueriwieneu.ch/photo/4.0.jpeg?bfbb...,Web interface,Diese Reparatur wird von uns in den kommenden ...,Beim Trotto: Beim Trottoir sind einige Randste...,https://www.zueriwieneu.ch/report/4,POINT (2684605 1251431)
3,4,5,2013-03-15T09:17:15,2013-03-20T10:05:05,2013-04-12T08:09:05,2681754,1250376,Strasse/Trottoir/Platz,Strasse/Trottoir/Platz,fixed - council,16624,Auf dem Par,Auf dem Parkplatz beim Waidspital sind einige ...,https://www.zueriwieneu.ch/photo/5.0.jpeg?e309...,Web interface,Diese Reparatur wird von uns in den kommenden ...,Auf dem Par: Auf dem Parkplatz beim Waidspital...,https://www.zueriwieneu.ch/report/5,POINT (2681754 1250376)
4,5,6,2013-03-15T10:36:53,2013-04-22T18:25:05,2013-04-23T13:50:33,2683094,1247762,Abfall/Sammelstelle,Abfall/Sammelstelle,fixed - council,16624,Arbeitskist,Arbeitskiste ist rund herum verschmiert,https://www.zueriwieneu.ch/photo/6.0.jpeg?8e65...,Web interface,Dieses Graffiti wird von uns in den kommenden ...,Arbeitskist: Arbeitskiste ist rund herum versc...,https://www.zueriwieneu.ch/report/6,POINT (2683094 1247762)
5,6,7,2013-03-16T17:54:42,2013-03-28T07:10:05,2013-04-12T08:09:44,2683475,1247422,Strasse/Trottoir/Platz,Strasse/Trottoir/Platz,fixed - council,16624,Gelockerte,Gelockerte und fehlende Pflastersteine auf der...,https://www.zueriwieneu.ch/photo/7.0.jpeg?eefa...,Web interface,Diese Reparatur wird von uns in den kommenden ...,Gelockerte : Gelockerte und fehlende Pflasters...,https://www.zueriwieneu.ch/report/7,POINT (2683475 1247422)
6,7,8,2013-03-16T18:04:21,2013-05-06T15:50:05,2013-05-06T17:29:11,2683303,1247675,Strasse/Trottoir/Platz,Strasse/Trottoir/Platz,fixed - council,16624,Steinerne B,"Steinerne Ballustrade bei der Uraniawache, Bah...",https://www.zueriwieneu.ch/photo/8.0.jpeg?9461...,Web interface,Für diesen Bereich ist die Immobilienbewirtsch...,Steinerne B: Steinerne Ballustrade bei der Ura...,https://www.zueriwieneu.ch/report/8,POINT (2683303 1247675)
7,8,9,2013-03-18T07:06:53,2013-03-19T17:10:05,2013-04-12T08:18:43,2678769,1248921,Strasse/Trottoir/Platz,Strasse/Trottoir/Platz,fixed - council,16624,Feldblumens,"Feldblumenstrasse 30, Schlagloch",NaN,Web interface,Diese Reparatur wird von uns in den kommenden ...,"Feldblumens: Feldblumenstrasse 30, Schlagloch",https://www.zueriwieneu.ch/report/9,POINT (2678769 1248921)
8,9,10,2013-03-18T07:16:54,2013-03-19T09:40:05,2013-04-12T08:19:25,2678479,1248732,Strasse/Trottoir/Platz,Strasse/Trottoir/Platz,fixed - council,16624,Rautistrass,Rautistrasse / Friedhofstrasse: Schlagloch im ...,NaN,Web interface,Diese Reparatur wird von uns in den kommenden ...,Rautistrass: Rautistrasse / Friedhofstrasse: S...,https://www.zueriwieneu.ch/report/10,POINT (2678479 1248732)
9,10,11,2013-03-20T07:20:37,2013-03-20T10:05:05,2013-04-12T08:11:54,2682529,1251346,Strasse/Trottoir/Platz,Strasse/Trottoir/Platz,fixed - council,16624,Neben dem S,Neben dem Schacht sind ca. 2 m Wassersteine ab...,NaN,Web interface,Diese Reparatur wird von uns in den kommenden ...,Neben dem S: Neben dem Schacht sind ca. 2 m Wa...,https://www.zueriwieneu.ch/report/11,POINT (2682529 1251346)

,objectid,service_request_id,requested_datetime,agency_sent_datetime,updated_datetime,e,n,service_code,service_name,status,userid,title,detail,media_url,interface_used,service_notice,description,url,geometry
72918,72919,81475,2026-05-08T09:43:08,2026-05-08T09:47:05,2026-05-08T11:20:47,2681853,1246346,Abfall/Sammelstelle,Abfall/Sammelstelle,fixed - council,3029,Ein Sofa li,Ein Sofa liegt unter der Brücke.,https://www.zueriwieneu.ch/photo/81475.0.jpeg?...,mobile,Entsorgung + Recycling Zürich holt den gemelde...,Ein Sofa li: Ein Sofa liegt unter der Brücke.,https://www.zueriwieneu.ch/report/81475,POINT (2681853 1246346)
72919,72920,81477,2026-05-08T10:39:03,2026-05-08T11:12:05,2026-05-08T11:12:05,2681282,1242686,Allgemein,Allgemein,external,3971,Dieser Roll,Dieser Roller steht schon seit 3 Wochen auf de...,https://www.zueriwieneu.ch/photo/81477.0.jpeg?...,desktop,Vielen Dank für Ihre Meldung. Wir haben sie an...,Dieser Roll: Dieser Roller steht schon seit 3 ...,https://www.zueriwieneu.ch/report/81477,POINT (2681282 1242686)
72920,72921,81478,2026-05-08T10:52:45,2026-05-08T10:57:05,2026-05-08T12:22:43,2684828,1251822,Abfall/Sammelstelle,Abfall/Sammelstelle,fixed - council,12710,Gruezi mite,Gruezi mitenand Da wurde offebar diese Woche n...,NaN,iOS,Entsorgung + Recycling Zürich leitet Ihr Anlie...,Gruezi mite: Gruezi mitenand Da wurde offebar ...,https://www.zueriwieneu.ch/report/81478,POINT (2684828 1251822)
72921,72922,81479,2026-05-08T11:00:26,2026-05-08T11:02:07,2026-05-08T11:25:56,2681016,1249418,Beleuchtung/Uhren,Beleuchtung/Uhren,fixed - council,6076,Light on du,Light on during day,NaN,iOS,Besten Dank für Ihre Nachricht. <br/> Dass die...,Light on du: Light on during day,https://www.zueriwieneu.ch/report/81479,POINT (2681016 1249418)
72922,72923,81480,2026-05-08T11:08:39,2026-05-08T11:12:05,2026-05-08T17:19:05,2678944,1247548,Schädlinge,Schädlinge,fixed - council,18925,Warscheinli,Warscheinlich Gespinstmotte¨ <br/> <br/> Bin ...,https://www.zueriwieneu.ch/photo/81480.0.jpeg?...,desktop,Vielen Dank für Ihre Meldung. Die Gespinstmott...,Warscheinli: Warscheinlich Gespinstmotte¨ <br/...,https://www.zueriwieneu.ch/report/81480,POINT (2678944 1247548)
72923,72924,81485,2026-05-08T12:35:15,2026-05-08T12:37:06,2026-05-08T13:37:04,2680717,1246225,Signalisation/Lichtsignal,Signalisation/Lichtsignal,fixed - council,16680,HV Tafel ve,HV Tafel verdreht,https://www.zueriwieneu.ch/photo/81485.0.jpeg?...,iOS,Guten Tag und vielen Dank für Ihre Meldung. <b...,HV Tafel ve: HV Tafel verdreht,https://www.zueriwieneu.ch/report/81485,POINT (2680717 1246225)
72924,72925,81488,2026-05-08T14:22:41,2026-05-08T14:27:06,2026-05-08T16:40:54,2681081,1248091,Abfall/Sammelstelle,Abfall/Sammelstelle,fixed - council,14824,Teppich,Teppich,https://www.zueriwieneu.ch/photo/81488.0.jpeg?...,iOS,Entsorgung + Recycling Zürich holt den gemelde...,Teppich: Teppich,https://www.zueriwieneu.ch/report/81488,POINT (2681081 1248091)
72925,72926,81489,2026-05-08T14:48:24,2026-05-08T14:52:05,2026-05-08T15:23:37,2686121,1246921,Signalisation/Lichtsignal,Signalisation/Lichtsignal,fixed - council,14768,Markierung,Markierung ist nicht abgeschlossen oder fehlt.,NaN,iOS,Guten Tag <br/> <br/> Vielen Dank für Ihren w...,Markierung : Markierung ist nicht abgeschlosse...,https://www.zueriwieneu.ch/report/81489,POINT (2686121 1246921)
72926,72927,81491,2026-05-08T15:13:14,2026-05-08T15:17:06,2026-05-08T15:25:27,2681238,1247791,Signalisation/Lichtsignal,Signalisation/Lichtsignal,fixed - council,17363,HV Tafel ve,HV Tafel verklebt,https://www.zueriwieneu.ch/photo/81491.0.jpeg?...,iOS,Guten Tag <br/> <br/> Vielen Dank für Ihren w...,HV Tafel ve: HV Tafel verklebt,https://www.zueriwieneu.ch/report/81491,POINT (2681238 1247791)
72927,72928,81493,2026-05-08T15:49:21,2026-05-08T15:52:05,2026-05-08T16:23:23,2681239,1247764,Signalisation/Lichtsignal,Signalisation/Lichtsignal,fixed - council,17363,HV Tafel ve,HV Tafel verklebt und abgedreht.,https://www.zueriwieneu.ch/photo/81493.0.jpeg?...,iOS,Guten Tag <br/> <br/> Vielen Dank für Ihren w...,HV Tafel ve: HV Tafel verklebt und abgedreht.,https://www.zueriwieneu.ch/report/81493,POINT (2681239 1247764)

(72928, 19)
<ArrowStringArray>
[            'objectid',   'service_request_id',   'requested_datetime',
 'agency_sent_datetime',     'updated_datetime',                    'e',
                    'n',         'service_code',         'service_name',
               'status',               'userid',                'title',
               'detail',            'media_url',       'interface_used',
       'service_notice',          'description',                  'url',
             'geometry']
Length: 19, dtype: str
<class 'pandas.DataFrame'>
RangeIndex: 72928 entries, 0 to 72927
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   objectid              72928 non-null  int64
 1   service_request_id    72928 non-null  int64
 2   requested_datetime    72928 non-null  str
 3   agency_sent_datetime  72104 non-null  str
 4   updated_datetime      72928 non-null  str
 5   e                     72928 non-null  int64
 6   n                     72928 non-null  int64
 7   service_code          72928 non-null  str
 8   service_name          72928 non-null  str
 9   status                72928 non-null  str
 10  userid                72928 non-null  int64
 11  title                 72926 non-null  str
 12  detail                72926 non-null  str
 13  media_url             50194 non-null  str
 14  interface_used        72928 non-null  str
 15  service_notice        72075 non-null  str
 16  description           72928 non-null  str
 17  url                   72928 non-null  str
 18  geometry              72928 non-null  str
dtypes: int64(5), str(14)
memory usage: 59.6 MB

None

In [9]:
zwn_df["requested_datetime"] = pd.to_datetime(zwn_df["requested_datetime"])
zwn_df["agency_sent_datetime"] = pd.to_datetime(zwn_df["agency_sent_datetime"])
zwn_df["updated_datetime"] = pd.to_datetime(zwn_df["updated_datetime"])

In [11]:
display(zwn_df.info())
display(zwn_df.head(10))

<class 'pandas.DataFrame'>
RangeIndex: 72928 entries, 0 to 72927
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   objectid              72928 non-null  int64
 1   service_request_id    72928 non-null  int64
 2   requested_datetime    72928 non-null  datetime64[us]
 3   agency_sent_datetime  72104 non-null  datetime64[us]
 4   updated_datetime      72928 non-null  datetime64[us]
 5   e                     72928 non-null  int64
 6   n                     72928 non-null  int64
 7   service_code          72928 non-null  str
 8   service_name          72928 non-null  str
 9   status                72928 non-null  str
 10  userid                72928 non-null  int64
 11  title                 72926 non-null  str
 12  detail                72926 non-null  str
 13  media_url             50194 non-null  str
 14  interface_used        72928 non-null  str
 15  service_notice        72075 non-null  str
 16  description           72928 non-null  str
 17  url                   72928 non-null  str
 18  geometry              72928 non-null  str
dtypes: datetime64[us](3), int64(5), str(11)
memory usage: 55.6 MB

None

,objectid,service_request_id,requested_datetime,agency_sent_datetime,updated_datetime,e,n,service_code,service_name,status,userid,title,detail,media_url,interface_used,service_notice,description,url,geometry
0,1,1,2013-03-14 15:16:15,2013-04-04 07:25:05,2013-04-12 07:59:30,2678968,1247548,Strasse/Trottoir/Platz,Strasse/Trottoir/Platz,fixed - council,16624,Auf dem Asp,Auf dem Asphalt des Bürgersteigs hat es eine E...,NaN,Web interface,Diese Reparatur wird von uns in den kommenden ...,Auf dem Asp: Auf dem Asphalt des Bürgersteigs ...,https://www.zueriwieneu.ch/report/1,POINT (2678968 1247548)
1,2,2,2013-03-14 15:17:57,2013-03-26 14:05:05,2013-04-12 08:00:22,2680746,1249916,Strasse/Trottoir/Platz,Strasse/Trottoir/Platz,fixed - council,16624,Vermessungs,Vermessungspunkt ist nicht mehr bündig mit dem...,NaN,Web interface,Diese Reparatur wird von uns in den kommenden ...,Vermessungs: Vermessungspunkt ist nicht mehr b...,https://www.zueriwieneu.ch/report/2,POINT (2680746 1249916)
2,3,4,2013-03-15 09:14:16,2013-03-15 09:55:05,2013-04-12 08:08:10,2684605,1251431,Strasse/Trottoir/Platz,Strasse/Trottoir/Platz,fixed - council,16624,Beim Trotto,Beim Trottoir sind einige Randsteine defekt un...,https://www.zueriwieneu.ch/photo/4.0.jpeg?bfbb...,Web interface,Diese Reparatur wird von uns in den kommenden ...,Beim Trotto: Beim Trottoir sind einige Randste...,https://www.zueriwieneu.ch/report/4,POINT (2684605 1251431)
3,4,5,2013-03-15 09:17:15,2013-03-20 10:05:05,2013-04-12 08:09:05,2681754,1250376,Strasse/Trottoir/Platz,Strasse/Trottoir/Platz,fixed - council,16624,Auf dem Par,Auf dem Parkplatz beim Waidspital sind einige ...,https://www.zueriwieneu.ch/photo/5.0.jpeg?e309...,Web interface,Diese Reparatur wird von uns in den kommenden ...,Auf dem Par: Auf dem Parkplatz beim Waidspital...,https://www.zueriwieneu.ch/report/5,POINT (2681754 1250376)
4,5,6,2013-03-15 10:36:53,2013-04-22 18:25:05,2013-04-23 13:50:33,2683094,1247762,Abfall/Sammelstelle,Abfall/Sammelstelle,fixed - council,16624,Arbeitskist,Arbeitskiste ist rund herum verschmiert,https://www.zueriwieneu.ch/photo/6.0.jpeg?8e65...,Web interface,Dieses Graffiti wird von uns in den kommenden ...,Arbeitskist: Arbeitskiste ist rund herum versc...,https://www.zueriwieneu.ch/report/6,POINT (2683094 1247762)
5,6,7,2013-03-16 17:54:42,2013-03-28 07:10:05,2013-04-12 08:09:44,2683475,1247422,Strasse/Trottoir/Platz,Strasse/Trottoir/Platz,fixed - council,16624,Gelockerte,Gelockerte und fehlende Pflastersteine auf der...,https://www.zueriwieneu.ch/photo/7.0.jpeg?eefa...,Web interface,Diese Reparatur wird von uns in den kommenden ...,Gelockerte : Gelockerte und fehlende Pflasters...,https://www.zueriwieneu.ch/report/7,POINT (2683475 1247422)
6,7,8,2013-03-16 18:04:21,2013-05-06 15:50:05,2013-05-06 17:29:11,2683303,1247675,Strasse/Trottoir/Platz,Strasse/Trottoir/Platz,fixed - council,16624,Steinerne B,"Steinerne Ballustrade bei der Uraniawache, Bah...",https://www.zueriwieneu.ch/photo/8.0.jpeg?9461...,Web interface,Für diesen Bereich ist die Immobilienbewirtsch...,Steinerne B: Steinerne Ballustrade bei der Ura...,https://www.zueriwieneu.ch/report/8,POINT (2683303 1247675)
7,8,9,2013-03-18 07:06:53,2013-03-19 17:10:05,2013-04-12 08:18:43,2678769,1248921,Strasse/Trottoir/Platz,Strasse/Trottoir/Platz,fixed - council,16624,Feldblumens,"Feldblumenstrasse 30, Schlagloch",NaN,Web interface,Diese Reparatur wird von uns in den kommenden ...,"Feldblumens: Feldblumenstrasse 30, Schlagloch",https://www.zueriwieneu.ch/report/9,POINT (2678769 1248921)
8,9,10,2013-03-18 07:16:54,2013-03-19 09:40:05,2013-04-12 08:19:25,2678479,1248732,Strasse/Trottoir/Platz,Strasse/Trottoir/Platz,fixed - council,16624,Rautistrass,Rautistrasse / Friedhofstrasse: Schlagloch im ...,NaN,Web interface,Diese Reparatur wird von uns in den kommenden ...,Rautistrass: Rautistrasse / Friedhofstrasse: S...,https://www.zueriwieneu.ch/report/10,POINT (2678479 1248732)
9,10,11,2013-03-20 07:20:37,2013-03-20 10:05:05,2013-04-12 08:11:54,2682529,1251346,Strasse/Trottoir/Platz,Strasse/Trottoir/Platz,fixed - council,16624,Neben dem S,Neben dem Schacht sind ca. 2 m Wassersteine ab...,NaN,Web interface,Diese Reparatur wird von uns in den kommenden ...,Neben dem S: Neben dem Schacht sind ca. 2 m Wa...,https://www.zueriwieneu.ch/report/11,POINT (2682529 1251346)

In [13]:
# 1. Make a safe copy
zwn_interp = zwn_df.copy()

# 2. Use interpolate() to connect the dots between the day before and day after
zwn_interp["agency_sent_datetime"] = zwn_interp["agency_sent_datetime"].interpolate()

display(zwn_interp.info())
display(zwn_interp.head(4))

<class 'pandas.DataFrame'>
RangeIndex: 72928 entries, 0 to 72927
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   objectid              72928 non-null  int64
 1   service_request_id    72928 non-null  int64
 2   requested_datetime    72928 non-null  datetime64[us]
 3   agency_sent_datetime  72928 non-null  datetime64[us]
 4   updated_datetime      72928 non-null  datetime64[us]
 5   e                     72928 non-null  int64
 6   n                     72928 non-null  int64
 7   service_code          72928 non-null  str
 8   service_name          72928 non-null  str
 9   status                72928 non-null  str
 10  userid                72928 non-null  int64
 11  title                 72926 non-null  str
 12  detail                72926 non-null  str
 13  media_url             50194 non-null  str
 14  interface_used        72928 non-null  str
 15  service_notice        72075 non-null  str
 16  description           72928 non-null  str
 17  url                   72928 non-null  str
 18  geometry              72928 non-null  str
dtypes: datetime64[us](3), int64(5), str(11)
memory usage: 55.6 MB

None

,objectid,service_request_id,requested_datetime,agency_sent_datetime,updated_datetime,e,n,service_code,service_name,status,userid,title,detail,media_url,interface_used,service_notice,description,url,geometry
0,1,1,2013-03-14 15:16:15,2013-04-04 07:25:05,2013-04-12 07:59:30,2678968,1247548,Strasse/Trottoir/Platz,Strasse/Trottoir/Platz,fixed - council,16624,Auf dem Asp,Auf dem Asphalt des Bürgersteigs hat es eine E...,NaN,Web interface,Diese Reparatur wird von uns in den kommenden ...,Auf dem Asp: Auf dem Asphalt des Bürgersteigs ...,https://www.zueriwieneu.ch/report/1,POINT (2678968 1247548)
1,2,2,2013-03-14 15:17:57,2013-03-26 14:05:05,2013-04-12 08:00:22,2680746,1249916,Strasse/Trottoir/Platz,Strasse/Trottoir/Platz,fixed - council,16624,Vermessungs,Vermessungspunkt ist nicht mehr bündig mit dem...,NaN,Web interface,Diese Reparatur wird von uns in den kommenden ...,Vermessungs: Vermessungspunkt ist nicht mehr b...,https://www.zueriwieneu.ch/report/2,POINT (2680746 1249916)
2,3,4,2013-03-15 09:14:16,2013-03-15 09:55:05,2013-04-12 08:08:10,2684605,1251431,Strasse/Trottoir/Platz,Strasse/Trottoir/Platz,fixed - council,16624,Beim Trotto,Beim Trottoir sind einige Randsteine defekt un...,https://www.zueriwieneu.ch/photo/4.0.jpeg?bfbb...,Web interface,Diese Reparatur wird von uns in den kommenden ...,Beim Trotto: Beim Trottoir sind einige Randste...,https://www.zueriwieneu.ch/report/4,POINT (2684605 1251431)
3,4,5,2013-03-15 09:17:15,2013-03-20 10:05:05,2013-04-12 08:09:05,2681754,1250376,Strasse/Trottoir/Platz,Strasse/Trottoir/Platz,fixed - council,16624,Auf dem Par,Auf dem Parkplatz beim Waidspital sind einige ...,https://www.zueriwieneu.ch/photo/5.0.jpeg?e309...,Web interface,Diese Reparatur wird von uns in den kommenden ...,Auf dem Par: Auf dem Parkplatz beim Waidspital...,https://www.zueriwieneu.ch/report/5,POINT (2681754 1250376)