In [1]:
from pathlib import Path
import os

#Nachfragen wie man das elegante lösen könnte!

# Immer sicher: Projektroot anhand dieser Datei bestimmen
notebook_dir = Path(os.getcwd())

# Nur hochgehen wenn wir noch in notebooks/ sind
if notebook_dir.name == "notebooks":
    os.chdir(notebook_dir.parent)

print(os.getcwd())  # Kontrolle: muss in sds210-final-project enden

/Users/christophhueppi/Documents/Universität_Zürich/Geographie/Master/FS-26/GEO-876/sds210-final-project

In [2]:
import pandas as pd

# 1. Load, sep=";" or "," test it!
zh_pop_df = pd.read_csv("data/raw/Bevölkerungsentwicklung_Stadtkreis_Stadtquartier.csv", sep=";", encoding="utf-8")

print("Data loaded successfully!")

# 2. Peek
display(zh_pop_df.head(10))
display(zh_pop_df.tail(10))

# 3. Shape & Columnsb
print(zh_pop_df.shape)
print(zh_pop_df.columns.values)
display(zh_pop_df.info())

Data loaded successfully!

,districts,1930,1941,1950,1960,1970,1980,1990,2000,2010,2020,2025
0,Ganze Stadt,290 937,336 531,389 573,437 273,417 972,370 618,356 352,360 980,385 468,434 736,452 421
1,Kreis 1,21 824,20 017,17 618,14 293,10 270,7 008,5 691,5 786,5 563,5 831,5 747
2,Rathaus,10 548,9 018,8 096,6 681,4 916,3 539,3 145,3 109,3 099,3 317,3 252
3,Hochschulen,2 833,2 866,2 590,1 986,1 459,1 034,789,759,678,675,688
4,Lindenhof,4 053,3 671,3 330,2 785,2 075,1 331,930,989,951,1 010,1 038
5,City,4 390,4 462,3 602,2 841,1 820,1 104,827,929,835,829,769
6,Kreis 2,21 719,28 901,33 461,36 624,33 704,30 505,28 466,28 935,29 878,35 552,38 360
7,Wollishofen,9 067,13 874,17 036,19 684,18 372,16 708,15 798,16 102,15 988,19 757,22 029
8,Leimbach,682,1 177,2 225,3 032,3 859,4 635,4 586,4 644,5 293,6 140,6 316
9,Enge,11 970,13 850,14 200,13 908,11 473,9 162,8 082,8 189,8 597,9 655,10 015

,districts,1930,1941,1950,1960,1970,1980,1990,2000,2010,2020,2025
37,Höngg,5 307,7 276,8 878,14 617,17 059,16 953,19 150,20 423,21 179,24 439,24 981
38,Wipkingen,19 788,21 518,22 037,21 135,19 336,16 548,15 744,15 704,15 700,16 605,16 745
39,Kreis 11,20 684,27 394,37 733,53 457,57 376,52 994,51 930,54 133,65 796,76 188,80 964
40,Affoltern,2 570,3 347,6 774,14 623,17 859,17 966,18 084,18 387,22 972,26 584,27 439
41,Oerlikon,12 502,16 799,18 445,21 727,19 534,16 558,16 399,17 876,20 787,23 548,24 205
42,Seebach,5 612,7 248,12 514,17 107,19 983,18 470,17 447,17 870,22 037,26 056,29 320
43,Kreis 12,2 460,3 237,13 930,33 360,33 869,29 456,27 547,28 098,29 537,32 845,32 832
44,Saatlen,182,582,5 754,7 957,7 297,6 834,6 428,6 338,7 175,8 799,8 852
45,Schwamendingen-Mitte,2 104,2 357,4 872,12 107,12 849,10 961,10 161,10 479,10 903,11 083,11 383
46,Hirzenbach,174,298,3 304,13 296,13 723,11 661,10 958,11 281,11 459,12 963,12 597

(47, 12)
<ArrowStringArray>
['districts',      '1930',      '1941',      '1950',      '1960',      '1970',
      '1980',      '1990',      '2000',      '2010',      '2020',      '2025']
Length: 12, dtype: str
<class 'pandas.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   districts  47 non-null     str
 1   1930       47 non-null     str
 2   1941       47 non-null     str
 3   1950       47 non-null     str
 4   1960       47 non-null     str
 5   1970       47 non-null     str
 6   1980       47 non-null     str
 7   1990       47 non-null     str
 8   2000       47 non-null     str
 9   2010       47 non-null     str
 10  2020       47 non-null     str
 11  2025       47 non-null     str
dtypes: str(12)
memory usage: 9.3 KB

None

In [3]:
for col in zh_pop_df.columns:
    print(f"{col}: {zh_pop_df[col].head(10).tolist()}")

districts: ['Ganze Stadt', 'Kreis 1', 'Rathaus', 'Hochschulen', 'Lindenhof', 'City', 'Kreis 2', 'Wollishofen', 'Leimbach', 'Enge']
1930: ['\xa0290\xa0937', '\xa021\xa0824', '\xa010\xa0548', '\xa02\xa0833', '\xa04\xa0053', '\xa04\xa0390', '\xa021\xa0719', '\xa09\xa0067', '\xa0\xa0682', '\xa011\xa0970']
1941: ['\xa0336\xa0531', '\xa020\xa0017', '\xa09\xa0018', '\xa02\xa0866', '\xa03\xa0671', '\xa04\xa0462', '\xa028\xa0901', '\xa013\xa0874', '\xa01\xa0177', '\xa013\xa0850']
1950: ['\xa0389\xa0573', '\xa017\xa0618', '\xa08\xa0096', '\xa02\xa0590', '\xa03\xa0330', '\xa03\xa0602', '\xa033\xa0461', '\xa017\xa0036', '\xa02\xa0225', '\xa014\xa0200']
1960: ['\xa0437\xa0273', '\xa014\xa0293', '\xa06\xa0681', '\xa01\xa0986', '\xa02\xa0785', '\xa02\xa0841', '\xa036\xa0624', '\xa019\xa0684', '\xa03\xa0032', '\xa013\xa0908']
1970: ['\xa0417\xa0972', '\xa010\xa0270', '\xa04\xa0916', '\xa01\xa0459', '\xa02\xa0075', '\xa01\xa0820', '\xa033\xa0704', '\xa018\xa0372', '\xa03\xa0859', '\xa011\xa0473']
1980: ['\xa0370\xa0618', '\xa07\xa0008', '\xa03\xa0539', '\xa01\xa0034', '\xa01\xa0331', '\xa01\xa0104', '\xa030\xa0505', '\xa016\xa0708', '\xa04\xa0635', '\xa09\xa0162']
1990: ['\xa0356\xa0352', '\xa05\xa0691', '\xa03\xa0145', '\xa0\xa0789', '\xa0\xa0930', '\xa0\xa0827', '\xa028\xa0466', '\xa015\xa0798', '\xa04\xa0586', '\xa08\xa0082']
2000: ['\xa0360\xa0980', '\xa05\xa0786', '\xa03\xa0109', '\xa0\xa0759', '\xa0\xa0989', '\xa0\xa0929', '\xa028\xa0935', '\xa016\xa0102', '\xa04\xa0644', '\xa08\xa0189']
2010: ['\xa0385\xa0468', '\xa05\xa0563', '\xa03\xa0099', '\xa0\xa0678', '\xa0\xa0951', '\xa0\xa0835', '\xa029\xa0878', '\xa015\xa0988', '\xa05\xa0293', '\xa08\xa0597']
2020: ['\xa0434\xa0736', '\xa05\xa0831', '\xa03\xa0317', '\xa0\xa0675', '\xa01\xa0010', '\xa0\xa0829', '\xa035\xa0552', '\xa019\xa0757', '\xa06\xa0140', '\xa09\xa0655']
2025: ['\xa0452\xa0421', '\xa05\xa0747', '\xa03\xa0252', '\xa0\xa0688', '\xa01\xa0038', '\xa0\xa0769', '\xa038\xa0360', '\xa022\xa0029', '\xa06\xa0316', '\xa010\xa0015']

In [4]:
# Alle Spalten die als Jahreszahl erkennbar sind
year_cols = [col for col in zh_pop_df.columns if col.isdigit()]
print(year_cols)  # Kontrolle

# Alle Jahres-Spalten auf einmal konvertieren
zh_pop_df[year_cols] = zh_pop_df[year_cols].apply(
    lambda col: pd.to_numeric(col.str.replace(r"[^\d]", "", regex=True), errors="coerce")
)

# 2. Peek
display(zh_pop_df.head(10))
display(zh_pop_df.tail(10))

# 3. Shape & Columns
print(zh_pop_df.shape)
print(zh_pop_df.columns.values)
display(zh_pop_df.info())

['1930', '1941', '1950', '1960', '1970', '1980', '1990', '2000', '2010', '2020', '2025']

,districts,1930,1941,1950,1960,1970,1980,1990,2000,2010,2020,2025
0,Ganze Stadt,290937,336531,389573,437273,417972,370618,356352,360980,385468,434736,452421
1,Kreis 1,21824,20017,17618,14293,10270,7008,5691,5786,5563,5831,5747
2,Rathaus,10548,9018,8096,6681,4916,3539,3145,3109,3099,3317,3252
3,Hochschulen,2833,2866,2590,1986,1459,1034,789,759,678,675,688
4,Lindenhof,4053,3671,3330,2785,2075,1331,930,989,951,1010,1038
5,City,4390,4462,3602,2841,1820,1104,827,929,835,829,769
6,Kreis 2,21719,28901,33461,36624,33704,30505,28466,28935,29878,35552,38360
7,Wollishofen,9067,13874,17036,19684,18372,16708,15798,16102,15988,19757,22029
8,Leimbach,682,1177,2225,3032,3859,4635,4586,4644,5293,6140,6316
9,Enge,11970,13850,14200,13908,11473,9162,8082,8189,8597,9655,10015

,districts,1930,1941,1950,1960,1970,1980,1990,2000,2010,2020,2025
37,Höngg,5307,7276,8878,14617,17059,16953,19150,20423,21179,24439,24981
38,Wipkingen,19788,21518,22037,21135,19336,16548,15744,15704,15700,16605,16745
39,Kreis 11,20684,27394,37733,53457,57376,52994,51930,54133,65796,76188,80964
40,Affoltern,2570,3347,6774,14623,17859,17966,18084,18387,22972,26584,27439
41,Oerlikon,12502,16799,18445,21727,19534,16558,16399,17876,20787,23548,24205
42,Seebach,5612,7248,12514,17107,19983,18470,17447,17870,22037,26056,29320
43,Kreis 12,2460,3237,13930,33360,33869,29456,27547,28098,29537,32845,32832
44,Saatlen,182,582,5754,7957,7297,6834,6428,6338,7175,8799,8852
45,Schwamendingen-Mitte,2104,2357,4872,12107,12849,10961,10161,10479,10903,11083,11383
46,Hirzenbach,174,298,3304,13296,13723,11661,10958,11281,11459,12963,12597

(47, 12)
<ArrowStringArray>
['districts',      '1930',      '1941',      '1950',      '1960',      '1970',
      '1980',      '1990',      '2000',      '2010',      '2020',      '2025']
Length: 12, dtype: str
<class 'pandas.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   districts  47 non-null     str
 1   1930       47 non-null     int64
 2   1941       47 non-null     int64
 3   1950       47 non-null     int64
 4   1960       47 non-null     int64
 5   1970       47 non-null     int64
 6   1980       47 non-null     int64
 7   1990       47 non-null     int64
 8   2000       47 non-null     int64
 9   2010       47 non-null     int64
 10  2020       47 non-null     int64
 11  2025       47 non-null     int64
dtypes: int64(11), str(1)
memory usage: 4.9 KB

None

In [5]:
# Save DataFrame to a new CSV file
# We use index=False to prevent saving the sequential row numbers
zh_pop_df.to_csv("data/processed/Bevölkerungsentwicklung_Stadtkreis_Stadtquartier_cleaned.csv", index=False)

print("File successfully saved!")

File successfully saved!

In [6]:
import pandas as pd
import numpy as np

zh_pop_interp = zh_pop_df.copy()

# Neue Jahres-Spalten hinzufügen
for year in range(2011, 2025):
    zh_pop_interp[str(year)] = np.nan

# Jahres-Spalten sortieren
year_cols = [str(y) for y in sorted(map(int, zh_pop_interp.columns[1:]))]

# districts + sortierte Jahres-Spalten
zh_pop_interp = zh_pop_interp[["districts"] + year_cols]

# Nur Jahresdaten interpolieren
zh_pop_interp[year_cols] = (
    zh_pop_interp[year_cols]
    .astype(float)
    .interpolate(axis=1)
    .round()
    .astype(int)
)

# 2. Peek
display(zh_pop_interp.head(10))
display(zh_pop_interp.tail(10))

# 3. Shape & Columns
print(zh_pop_interp.shape)
print(zh_pop_interp.columns.values)
display(zh_pop_interp.info())

,districts,1930,1941,1950,1960,1970,1980,1990,2000,2010,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Ganze Stadt,290937,336531,389573,437273,417972,370618,356352,360980,385468,...,412249,416713,421176,425640,430103,434567,439030,443494,447957,452421
1,Kreis 1,21824,20017,17618,14293,10270,7008,5691,5786,5563,...,5637,5649,5661,5673,5686,5698,5710,5722,5735,5747
2,Rathaus,10548,9018,8096,6681,4916,3539,3145,3109,3099,...,3160,3170,3181,3191,3201,3211,3221,3232,3242,3252
3,Hochschulen,2833,2866,2590,1986,1459,1034,789,759,678,...,682,683,683,684,685,685,686,687,687,688
4,Lindenhof,4053,3671,3330,2785,2075,1331,930,989,951,...,986,992,997,1003,1009,1015,1021,1026,1032,1038
5,City,4390,4462,3602,2841,1820,1104,827,929,835,...,809,804,800,795,791,787,782,778,773,769
6,Kreis 2,21719,28901,33461,36624,33704,30505,28466,28935,29878,...,33271,33836,34402,34967,35533,36098,36664,37229,37795,38360
7,Wollishofen,9067,13874,17036,19684,18372,16708,15798,16102,15988,...,18404,18807,19210,19613,20015,20418,20821,21224,21626,22029
8,Leimbach,682,1177,2225,3032,3859,4635,4586,4644,5293,...,5702,5770,5839,5907,5975,6043,6111,6180,6248,6316
9,Enge,11970,13850,14200,13908,11473,9162,8082,8189,8597,...,9164,9259,9353,9448,9542,9637,9731,9826,9920,10015

,districts,1930,1941,1950,1960,1970,1980,1990,2000,2010,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
37,Höngg,5307,7276,8878,14617,17059,16953,19150,20423,21179,...,22700,22953,23207,23460,23714,23967,24221,24474,24728,24981
38,Wipkingen,19788,21518,22037,21135,19336,16548,15744,15704,15700,...,16118,16188,16257,16327,16397,16466,16536,16606,16675,16745
39,Kreis 11,20684,27394,37733,53457,57376,52994,51930,54133,65796,...,71863,72874,73886,74897,75908,76919,77930,78942,79953,80964
40,Affoltern,2570,3347,6774,14623,17859,17966,18084,18387,22972,...,24759,25057,25354,25652,25950,26248,26546,26843,27141,27439
41,Oerlikon,12502,16799,18445,21727,19534,16558,16399,17876,20787,...,22154,22382,22610,22838,23066,23294,23521,23749,23977,24205
42,Seebach,5612,7248,12514,17107,19983,18470,17447,17870,22037,...,24950,25436,25921,26407,26892,27378,27863,28349,28834,29320
43,Kreis 12,2460,3237,13930,33360,33869,29456,27547,28098,29537,...,30855,31075,31294,31514,31734,31953,32173,32393,32612,32832
44,Saatlen,182,582,5754,7957,7297,6834,6428,6338,7175,...,7846,7958,8069,8181,8293,8405,8517,8628,8740,8852
45,Schwamendingen-Mitte,2104,2357,4872,12107,12849,10961,10161,10479,10903,...,11095,11127,11159,11191,11223,11255,11287,11319,11351,11383
46,Hirzenbach,174,298,3304,13296,13723,11661,10958,11281,11459,...,11914,11990,12066,12142,12218,12294,12369,12445,12521,12597

(47, 25)
<ArrowStringArray>
['districts',      '1930',      '1941',      '1950',      '1960',      '1970',
      '1980',      '1990',      '2000',      '2010',      '2011',      '2012',
      '2013',      '2014',      '2015',      '2016',      '2017',      '2018',
      '2019',      '2020',      '2021',      '2022',      '2023',      '2024',
      '2025']
Length: 25, dtype: str
<class 'pandas.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 25 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   districts  47 non-null     str
 1   1930       47 non-null     int64
 2   1941       47 non-null     int64
 3   1950       47 non-null     int64
 4   1960       47 non-null     int64
 5   1970       47 non-null     int64
 6   1980       47 non-null     int64
 7   1990       47 non-null     int64
 8   2000       47 non-null     int64
 9   2010       47 non-null     int64
 10  2011       47 non-null     int64
 11  2012       47 non-null     int64
 12  2013       47 non-null     int64
 13  2014       47 non-null     int64
 14  2015       47 non-null     int64
 15  2016       47 non-null     int64
 16  2017       47 non-null     int64
 17  2018       47 non-null     int64
 18  2019       47 non-null     int64
 19  2020       47 non-null     int64
 20  2021       47 non-null     int64
 21  2022       47 non-null     int64
 22  2023       47 non-null     int64
 23  2024       47 non-null     int64
 24  2025       47 non-null     int64
dtypes: int64(24), str(1)
memory usage: 9.7 KB

None

In [7]:
# Save DataFrame to a new CSV file
# We use index=False to prevent saving the sequential row numbers
zh_pop_interp.to_csv("data/processed/Bevölkerungsentwicklung_Stadtkreis_Stadtquartier_interpolated.csv", index=False)

print("File successfully saved!")

File successfully saved!

In [8]:
zh_pop_urbandists = zh_pop_interp.copy()

zh_pop_urbandists = zh_pop_urbandists[
    (~zh_pop_urbandists["districts"].str.startswith("Kreis")) &
    (zh_pop_urbandists["districts"] != "Ganze Stadt")
]

zh_pop_urbandists = zh_pop_urbandists.reset_index(drop=True)

# 2. Peek
display(zh_pop_urbandists.head(10))
display(zh_pop_urbandists.tail(10))

# 3. Shape & Columns
print(zh_pop_urbandists.shape)
print(zh_pop_urbandists.columns.values)
display(zh_pop_urbandists.info())

,districts,1930,1941,1950,1960,1970,1980,1990,2000,2010,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Rathaus,10548,9018,8096,6681,4916,3539,3145,3109,3099,...,3160,3170,3181,3191,3201,3211,3221,3232,3242,3252
1,Hochschulen,2833,2866,2590,1986,1459,1034,789,759,678,...,682,683,683,684,685,685,686,687,687,688
2,Lindenhof,4053,3671,3330,2785,2075,1331,930,989,951,...,986,992,997,1003,1009,1015,1021,1026,1032,1038
3,City,4390,4462,3602,2841,1820,1104,827,929,835,...,809,804,800,795,791,787,782,778,773,769
4,Wollishofen,9067,13874,17036,19684,18372,16708,15798,16102,15988,...,18404,18807,19210,19613,20015,20418,20821,21224,21626,22029
5,Leimbach,682,1177,2225,3032,3859,4635,4586,4644,5293,...,5702,5770,5839,5907,5975,6043,6111,6180,6248,6316
6,Enge,11970,13850,14200,13908,11473,9162,8082,8189,8597,...,9164,9259,9353,9448,9542,9637,9731,9826,9920,10015
7,Alt-Wiedikon,14017,17898,18507,17776,16386,13920,13679,14789,15988,...,17154,17349,17543,17738,17932,18126,18321,18515,18710,18904
8,Friesenberg,2670,4027,8127,9684,11263,10455,10037,9972,10596,...,10848,10890,10932,10974,11016,11058,11100,11142,11184,11226
9,Sihlfeld,22092,24222,27622,28308,25686,21775,20726,20887,20115,...,20660,20751,20842,20933,21024,21115,21205,21296,21387,21478

,districts,1930,1941,1950,1960,1970,1980,1990,2000,2010,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
24,Albisrieden,2898,5952,10922,18163,19218,17812,17083,16445,17835,...,20423,20854,21285,21716,22148,22579,23010,23441,23873,24304
25,Altstetten,9271,13651,18978,25030,27257,27642,27218,28174,30659,...,33145,33559,33974,34388,34802,35217,35631,36045,36460,36874
26,Höngg,5307,7276,8878,14617,17059,16953,19150,20423,21179,...,22700,22953,23207,23460,23714,23967,24221,24474,24728,24981
27,Wipkingen,19788,21518,22037,21135,19336,16548,15744,15704,15700,...,16118,16188,16257,16327,16397,16466,16536,16606,16675,16745
28,Affoltern,2570,3347,6774,14623,17859,17966,18084,18387,22972,...,24759,25057,25354,25652,25950,26248,26546,26843,27141,27439
29,Oerlikon,12502,16799,18445,21727,19534,16558,16399,17876,20787,...,22154,22382,22610,22838,23066,23294,23521,23749,23977,24205
30,Seebach,5612,7248,12514,17107,19983,18470,17447,17870,22037,...,24950,25436,25921,26407,26892,27378,27863,28349,28834,29320
31,Saatlen,182,582,5754,7957,7297,6834,6428,6338,7175,...,7846,7958,8069,8181,8293,8405,8517,8628,8740,8852
32,Schwamendingen-Mitte,2104,2357,4872,12107,12849,10961,10161,10479,10903,...,11095,11127,11159,11191,11223,11255,11287,11319,11351,11383
33,Hirzenbach,174,298,3304,13296,13723,11661,10958,11281,11459,...,11914,11990,12066,12142,12218,12294,12369,12445,12521,12597

(34, 25)
<ArrowStringArray>
['districts',      '1930',      '1941',      '1950',      '1960',      '1970',
      '1980',      '1990',      '2000',      '2010',      '2011',      '2012',
      '2013',      '2014',      '2015',      '2016',      '2017',      '2018',
      '2019',      '2020',      '2021',      '2022',      '2023',      '2024',
      '2025']
Length: 25, dtype: str
<class 'pandas.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 25 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   districts  34 non-null     str
 1   1930       34 non-null     int64
 2   1941       34 non-null     int64
 3   1950       34 non-null     int64
 4   1960       34 non-null     int64
 5   1970       34 non-null     int64
 6   1980       34 non-null     int64
 7   1990       34 non-null     int64
 8   2000       34 non-null     int64
 9   2010       34 non-null     int64
 10  2011       34 non-null     int64
 11  2012       34 non-null     int64
 12  2013       34 non-null     int64
 13  2014       34 non-null     int64
 14  2015       34 non-null     int64
 15  2016       34 non-null     int64
 16  2017       34 non-null     int64
 17  2018       34 non-null     int64
 18  2019       34 non-null     int64
 19  2020       34 non-null     int64
 20  2021       34 non-null     int64
 21  2022       34 non-null     int64
 22  2023       34 non-null     int64
 23  2024       34 non-null     int64
 24  2025       34 non-null     int64
dtypes: int64(24), str(1)
memory usage: 7.1 KB

None

In [9]:
# Save DataFrame to a new CSV file
# We use index=False to prevent saving the sequential row numbers
zh_pop_urbandists.to_csv("data/processed/Bevölkerungsentwicklung_Stadtkreis_Stadtquartier_urbandists.csv", index=False)

print("File successfully saved!")

File successfully saved!